export interface PATask {
  id: string;
  duty: string;
}

export const paTasks: PATask[] = [
  { id: '106', duty: 'Hair Care-Shampoo' },
  { id: '115', duty: 'Meal-Preparation' },
  { id: '116', duty: 'Housework-Chores' },
  { id: '117', duty: 'Managing-Finances' },
  { id: '118', duty: 'Managing-Medication' },
  { id: '119', duty: 'Shopping' },
  { id: '120', duty: 'Transportation' },
  { id: '122', duty: 'Hygiene' },
  { id: '123', duty: 'Dressing Upper' },
  { id: '124', duty: 'Dressing Lower' },
  { id: '125', duty: 'Locomotion' },
  { id: '126', duty: 'Transfer' },
  { id: '127', duty: 'Toilet Use' },
  { id: '128', duty: 'Bed Mobility' },
  { id: '129', duty: 'Eating' },
  { id: '130', duty: 'Bladder Incontinence' },
  { id: '131', duty: 'Bowel Incontinence' },
  { id: '134', duty: 'Bathing' },
  { id: '137', duty: 'Lotion/Ointment' },
  { id: '138', duty: 'Laundry' },
  { id: '139', duty: 'Reading/Writing' },
  { id: '140', duty: 'Supervision/Coaching/Cueing' },
  { id: '141', duty: 'Incontinence Care' },
  { id: '142', duty: 'Catheter Care' },
  { id: '143', duty: 'Wound Care' },
  { id: '145', duty: 'Stairs' },
  { id: '201', duty: 'In Person' },
  { id: '202', duty: 'Via Telephone' },
  { id: '205', duty: 'Bath-Shower' },
  { id: '206', duty: 'Bath-Bed' },
  { id: '208', duty: 'Mouth Care/Denture Care' },
  { id: '209', duty: 'Hair Care-Comb' },
  { id: '210', duty: 'Grooming-Shave' },
  { id: '212', duty: 'Grooming-Nails' },
  { id: '213', duty: 'Dressing' },
  { id: '214', duty: 'Skin Care' },
  { id: '215', duty: 'Foot Care' },
  { id: '218', duty: 'Toileting-Bedpan/Urinal' },
  { id: '219', duty: 'Toileting-Toilet' },
  { id: '220', duty: 'Patient is on a prescribed diet' },
  { id: '221', duty: 'Prepare-Breakfast' },
  { id: '222', duty: 'Prepare-Lunch' },
  { id: '223', duty: 'Prepare-Dinner' },
  { id: '224', duty: 'Prepare Snack' },
  { id: '225', duty: 'Assist with feeding' },
  { id: '228', duty: 'Transferring' },
  { id: '229', duty: 'Assist with walking' },
  { id: '230', duty: 'Patient walks with assistive devices' },
  { id: '231', duty: 'Assist with home exercise program' },
  { id: '232', duty: 'Range of Motion Exercises' },
  { id: '233', duty: 'Turning and positioning (At least Q2)' },
  { id: '235', duty: 'Take Temperature' },
  { id: '236', duty: 'Take Pulse' },
  { id: '237', duty: 'Take Blood Pressure' },
  { id: '239', duty: 'Take respirations' },
  { id: '241', duty: 'Assist with catheter care' },
  { id: '242', duty: 'Empty foley bag' },
  { id: '244', duty: 'Remind to take medication' },
  { id: '246', duty: 'Medication Reminders' },
  { id: '247', duty: 'Change bed linen' },
  { id: '248', duty: 'Patient Laundry' },
  { id: '249', duty: 'Light Housekeeping' },
  { id: '250', duty: 'Clean Bathroom' },
  { id: '252', duty: 'Do Patient shopping and errands' },
  { id: '253', duty: 'Accompany Patient to medical appointment' },
  { id: '256', duty: 'Others' }
];